// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	websocket "github.com/thecoderstudio/apollo-agent/websocket"
)

// Action is an autogenerated mock type for the Action type
type Action struct {
	mock.Mock
}

// Run provides a mock function with given fields:
func (_m *Action) Run() *chan websocket.Command {
	ret := _m.Called()

	var r0 *chan websocket.Command
	if rf, ok := ret.Get(0).(func() *chan websocket.Command); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chan websocket.Command)
		}
	}

	return r0
}

// execute provides a mock function with given fields:
func (_m *Action) execute() {
	_m.Called()
}
