// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	oauth "github.com/thecoderstudio/apollo-agent/oauth"
)

// AuthProvider is an autogenerated mock type for the AuthProvider type
type AuthProvider struct {
	mock.Mock
}

// GetAccessToken provides a mock function with given fields:
func (_m *AuthProvider) GetAccessToken() (oauth.AccessToken, error) {
	ret := _m.Called()

	var r0 oauth.AccessToken
	if rf, ok := ret.Get(0).(func() oauth.AccessToken); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(oauth.AccessToken)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetContinuousAccessToken provides a mock function with given fields:
func (_m *AuthProvider) GetContinuousAccessToken() (*chan oauth.AccessToken, *chan error) {
	ret := _m.Called()

	var r0 *chan oauth.AccessToken
	if rf, ok := ret.Get(0).(func() *chan oauth.AccessToken); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chan oauth.AccessToken)
		}
	}

	var r1 *chan error
	if rf, ok := ret.Get(1).(func() *chan error); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*chan error)
		}
	}

	return r0, r1
}
