// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	pty "github.com/thecoderstudio/apollo-agent/pty"

	websocket "github.com/thecoderstudio/apollo-agent/websocket"
)

// CommandExecutor is an autogenerated mock type for the CommandExecutor type
type CommandExecutor struct {
	mock.Mock
}

// Execute provides a mock function with given fields: session, command
func (_m *CommandExecutor) Execute(session pty.BaseSession, command websocket.Command) (*chan websocket.Command, error) {
	ret := _m.Called(session, command)

	var r0 *chan websocket.Command
	if rf, ok := ret.Get(0).(func(pty.BaseSession, websocket.Command) *chan websocket.Command); ok {
		r0 = rf(session, command)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chan websocket.Command)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(pty.BaseSession, websocket.Command) error); ok {
		r1 = rf(session, command)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
