name: Test

on:
  pull_request:
    branches:
    - develop
    - master
  push:
    branches:
    - develop
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.3'

      - name: Install zsh to test on multiple shells
        run: |
          sudo apt-get update
          sudo apt-get -y install zsh
          touch ~/.zshrc

      - name: Run tests
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage report
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)
