name: Test

on:
  pull_request:
    branches:
    - develop
    - master
  push:
    branches:
    - develop
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.3'

      - name: Install zsh to test on multiple shells
        run: |
          sudo apt-get update
          sudo apt-get -y install zsh
          touch ~/.zshrc
          cd /usr/local/share/zsh
          sudo chmod -R 755 ./site-functions
          sudo chown -R root:root ./site-functions

      - name: Run tests
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage report
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          CODECOV_BINARY_URL: https://uploader.codecov.io/latest/linux/codecov
          CODECOV_SHASUM_URL: https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
          CODECOV_SHASUM_SIGNATURE_URL: https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig
          CODECOV_PGP_KEY_URL: https://keybase.io/codecovsecurity/pgp_keys.asc
        run: |
          curl -s $CODECOV_BINARY_URL > codecov
          chmod +x codecov
          curl $CODECOV_PGP_KEY_URL | gpg --import
          curl -Os $CODECOV_SHASUM_URL
          curl -Os $CODECOV_SHASUM_SIGNATURE_URL
          gpg --verify codecov.SHA256SUM.sig codecov.SHA256SUM  \
            && sha256sum --check codecov.SHA256SUM \
            && ./codecov
